### ISSUE TITLE
My lists in PiHole are not updated.

### ISSUE THREAD

**Issue by ramazansancar** [sefinek24/Sefinek-Blocklist-Collection#21]
There is a problem on the server where the lists are stored.

![image](https://github.com/sefinek24/Sefinek-Blocklist-Collection/assets/8878055/a86e3d80-2423-48a1-8fda-50cba7ba9584)

![image](https://github.com/sefinek24/Sefinek-Blocklist-Collection/assets/8878055/181074fc-3771-4d89-b87a-3dce4022acdd)
![image](https://github.com/sefinek24/Sefinek-Blocklist-Collection/assets/8878055/04b07b5a-0b66-467c-9951-e271870292fe)

**Comment by sefinek** [comment]
Hi, I'm sorry for this issue. The server with the lists was globally unavailable, due to the VPS server memory running out. Unfortunately, 40GB is no longer sufficient, and I don't have the funds to cover the server costs. I've deleted useless logs on the server, hoping it will help at least for some time.

**Comment by ramazansancar** [comment]
@sefinek24 How about storing all the files somewhere like github, archive.org? 

There may be different alternatives. If you wish, I would like to support you in this regard. Open Source ❤

By the way, what is the current server cost?

**Comment by sefinek** [comment]
@ramazansancar Hello again!

The solution you propose would have made sense initially, of course, but currently, I think I will not consider the issue you mentioned. Mainly because I have to pay for the VPS anyway since I have a mail server set up on it, as well as another service that requires fast internet. Generally, I could host everything on my server at home, but then my internet would be inadequate for normal use, due to overload. Just downloading the blocklists would already take longer on the client's side. Additionally, I also do not have an external IP, which results in the inability to set up a mail server. So far, I've done everything using Cloudflare tunnels, making the mail server available to the world defeats the purpose. The mail recipient would have to have a [Cloudflare client](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads) installed. Anyway, thank you for your willingness.

Regarding the server costs, you'll need to check the prices on [OVH](https://www.ovhcloud.com/en/vps) yourself, as I dont want to provide a specific figure. I am currently using the VLE-2 offer. From what I also see, the prices in USD are different than in my currency. The VPS works great, the only flaw is the lack of free disk memory. Those block lists really need quite a lot of free space, especially since the server also hosts a GitHub Workflows service. Of course, the list of services on the server does not end there.

**Comment by ramazansancar** [comment]
> @ramazansancar Hello again!
> 
> The solution you propose would have made sense initially, of course, but currently, I think I will not consider the issue you mentioned. Mainly because I have to pay for the VPS anyway since I have a mail server set up on it, as well as another service that requires fast internet. Generally, I could host everything on my server at home, but then my internet would be inadequate for normal use, due to overload. Just downloading the blocklists would already take longer on the client's side. Additionally, I also do not have an external IP, which results in the inability to set up a mail server. So far, I've done everything using Cloudflare tunnels, making the mail server available to the world defeats the purpose. The mail recipient would have to have a [Cloudflare client](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads) installed. Anyway, thank you for your willingness.
> 
> Regarding the server costs, you'll need to check the prices on [OVH](https://www.ovhcloud.com/en/vps) yourself, as I dont want to provide a specific figure. I am currently using the VLE-2 offer. From what I also see, the prices in USD are different than in my currency. The VPS works great, the only flaw is the lack of free disk memory. Those block lists really need quite a lot of free space, especially since the server also hosts a GitHub Workflows service. Of course, the list of services on the server does not end there.

Creating a crontab that will automatically delete the logs seems to temporarily solve the problem. @sefinek24
