### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by whoot** [sefinek24/Sefinek-Blocklist-Collection#37]
The blocklist `blocklists/generated/0.0.0.0/gambling/TrustPositif/gambling-indonesia.fork.txt` contains the entry `postimg.cc` which is neither an indonesian site. nor a gambling site, but an image upload site.

**Comment by sefinek** [comment]
Added to the whitelist. Thanks!

**Comment by whoot** [comment]
Thanks, but why add it to the whitelist instead of removing the entry from the list?
I mean its clearly a false positive and shouldn't be in the list in the first place.

Another false positive is `i.ibb.co` in the same list. It's also an image upload site (belongs to imgbb.com).

**Comment by sefinek** [comment]
No worries, what is added to the whitelist will be removed from the designated files after a few minutes. And that's exactly what happened, check this commit: https://github.com/sefinek24/Sefinek-Blocklist-Collection/commit/59c2dea15d6aed82d279dc2bf6e02b984c4df64c

Around 1 AM Polish time, the domain you provided will also be removed on blocklist.sefinek.net. Check out https://blocklist.sefinek.net for more useful information.

Regarding issues with false positives, it happens that sites like i.ibb.co are mistakenly identified as dangerous by some antivirus programs, which may be due to the fact that they are sometimes used to host malicious files by third parties. However, these sites themselves are not malicious, see: [Malwarebytes Forums](https://forums.malwarebytes.com/topic/281837-iibbco-imgbbcom-false-positive) for example.

I have also added `i.ibb.co` to the whitelist in commit https://github.com/sefinek24/Sefinek-Blocklist-Collection/commit/a4762176163b72476e215dd7e20e26b66835ba2a. This triggered a [GitHub Actions](https://github.com/sefinek24/Sefinek-Blocklist-Collection/actions/runs/9518968179/job/26241120603) task. After a few minutes, a new commit was added (https://github.com/sefinek24/Sefinek-Blocklist-Collection/commit/ff59ab8b616987323a161644fdbf5a05e9caa3e6) that removed `i.ibb.co` from the `gambling/TrustPositif/gambling-indonesia.fork.txt` list. With the next list update, the excluded domain will of course be omitted.

```js
'gambling/TrustPositif/gambling-indonesia.fork.txt' => Set(2) { 'postimg.cc', 'i.ibb.co' }
```

**Comment by whoot** [comment]
Oh I see. Thanks for the explanation.
