### ISSUE TITLE
Blocking of LGBTQ+ helpful and friendly sites, describing as "useless"

### ISSUE THREAD

**Issue by VoxelTek** [sefinek24/Sefinek-Blocklist-Collection#4]
Hi there,

Within the list of "useless websites", there are quite a few that pertain to LGBTQ+ community members, many of which are harmless and potentially helpful. One such example is [`pfp.lgbt`](http://pfp.lgbt), which simply allows for the addition of pride banners to your profile picture. 

Given these websites are far from useless, and not malicious, could I ask they be removed from the list, or at the very least have a reasonable explanation provided for why they are present?

**Comment by VoxelTek** [comment]
While many of the sites within the list are rightfully there, many are not. I'd be curious why they have been placed there, and if it would be possible for them to be removed.

**Comment by sefinek24** [comment]
Hello,

in my opinion, the website `pfp.lgbt` is not necessary for anyone's life and clutters the internet. Expressing one's 'pride' on the internet should be gradually limited because a person's gender identity is a private matter, not a public one.

> Given these websites are far from useless, and not malicious

They are useless (for example 'pfp.lgbt'), because they don't teach anything . They don't contribute anything useful to the digital space.

> Many of which are harmless and potentially helpful

Sexualizing young peoples, in my view, is wrong and should be limited. Many people use AdBlockers to protect their families from potential dangers on the internet. It is mainly for this reason that these LGBT websites ended up on that list.

**Comment by Kimapr** [comment]
> a person's gender identity is a private matter, not a public one.

It isn't, really. Most non-LGBT people are very open about their gender identity. Some languages even force one to express gender when simply talking, like Russian.

**Comment by sefinek24** [comment]
Bruh, you misunderstood the context of my post. In my post, I was exclusively referring to the LGBT community. Your last sentence is absolutely correct and aligns with my opinion – in my native language, expressing gender in everyday speech is also natural. However, my post was about LGBT people who excessively promote their pronouns and impose them on others, which can be annoying. That's why I wrote that gender identity is a private matter.

I agree that most non-LGBT people openly talk about their gender identity. Some languages, like Russian or my native language, even force gender expression. However, my stance is solely about the LGBT community, which excessively highlights their pronouns. It is important to understand that for many people, the excessive promotion of gender identity (in the context of LGBT) can be exhausting and perceived as imposing their worldview.

Expressing gender in everyday conversation, such as in Russian, is normal and natural. I don't understand why you are bringing up something normal in the context of LGBT.

As for the Sefinek-Blocklist-Collection, we have always focused on safety and that will remain. Therefore, it includes lists of websites that may harm the youth. Currently, I am working on a crawler that indexes LGBTQ+ sites and adds them to the blacklist because, as I said, they are unnecessary (and even dangerous for young people). Gender identity or expressing pride in being, for example, bisexual should remain a private matter.

I am also sorry that you are encouraging your friends to dislike my post. After all, monkeys in a group are strong. I always knew that. Do you want a banana? 🍌

GitHub is not the place for such discussions. If you still disagree with my opinion, it's fine – everyone has the right to think differently. However, if you want to continue the conversation, I suggest moving it elsewhere. I have no problem expressing my views, including political ones. If you want, you can continue disliking my posts, but it won't change anything. Remember that GitHub is not YouTube. You will only waste your time. You can even DDoS my site, I totally don't care – it won't achieve anything anyway 🙀🙀
