### ISSUE TITLE
This link is blocked

### ISSUE THREAD

**Issue by medaminezghal** [sefinek24/Sefinek-Blocklist-Collection#66]
the catbox.moe is working but the subdomain doesn't: files.catbox.moe
i think this shouldn't be blocked

**Comment by sefinek** [comment]
Hi.

Unfortunately, I cannot add `files.catbox.moe` to the whitelist because `catbox.moe` lacks any form of antivirus scanning. A good comparison would be the website gamebanana.com. Although they have recently implemented file scanning on their server using ClamAV.

For example, consider the case with EICAR.COM: https://files.catbox.moe/ew6mkb.com  
The server allowed the upload of this file, which absolutely should not have happened.
<img width="1279" alt="{02380C22-FF20-4460-B433-7D80A4F0A11D}" src="https://github.com/user-attachments/assets/8cdb8ea4-d8d4-4204-9d9b-42a17ae5c85b">


For this reason, there is a high likelihood that the subdomain you provided may be sharing malware.

https://www.virustotal.com/gui/url/cde39249c878ad077a1e441bbba187a871b34607fb375d6b1b73f67a3c88fe64
https://www.virustotal.com/gui/domain/files.catbox.moe/relations

Thanks
