### ISSUE TITLE
[FALSE POSITIVE] Google scholar is marked as ads

### ISSUE THREAD

**Issue by Polpetta** [sefinek24/Sefinek-Blocklist-Collection#77]
Hello,
`scholar.google.com` is currently marked as "ads". This is a very useful website provided by Google to look and search for papers and academic studies :slightly_smiling_face: 

![image](https://github.com/user-attachments/assets/4a507637-2beb-40dc-8f24-3dfb1396ada5)

**Comment by sefinek** [comment]
Hi!

The list made by jerryn70 contains many false positives, so I completely removed it from the main collection some time ago. [Generate your list again](https://sefinek.net/blocklist-generator/pihole).

Your selections will be saved in cookies, so you don't need to download the TXT file.

Anyway, I will add `scholar.google.com` to the whitelist so that people won’t face similar issues in the future. Thanks!
Within 24 hours, the subdomain will be removed from the list.

Best regards,
Sefinek

**Comment by Polpetta** [comment]
Hi!

Thanks a lot for the heads up! I'll regenerate my list again 🙂 Many thanks for adding it to the whitelist anyway 🙌
